trigger:
  branches:
    include:
      - main  # Ajusta el nombre de la rama si es necesario

pool:
  name: 'LegalCC'

steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET Core SDK' # Opcional si tu proyecto lo requiere
    inputs:
      packageType: 'sdk'
      version: '6.x.x' # Ajusta según tu versión de .NET si es necesario

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQubeServiceConnection' # Nombre del servicio de conexión en Azure DevOps
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'LegalConnect'
      cliProjectName: 'LegalConnect'
      cliProjectVersion: '1.0'
      extraProperties: |
        sonar.language=php
        sonar.sources=.
        sonar.php.coverage.reportPaths=tests/coverage/coverage.xml
  
  - script: |
      # Comandos de construcción de tu proyecto
      echo "Compiling the project..."
      # Ejemplo de PHP
      composer install
    displayName: 'Compilar proyecto'
  
  - task: SonarQubeAnalyze@5
    displayName: 'Ejecutar análisis de SonarQube'

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publicar resultados en SonarQube'
